import logging

from htmlmin import minify
from pelican import signals

from plugins import find_html_files


logger = logging.getLogger(__name__)


def minify_html(pelican):
    """
    Minify all HTML files found in the configured output directory, overwriting
    the original file in the process.

    :param pelican: the Pelican instance
    """
    for filename in find_html_files(pelican):
        with open(filename, "r") as f:
            contents = f.read()

        try:
            contents = minify(contents)
            with open(filename, "w") as f:
                f.write(contents)
        except Exception as ex:
            logger.critical(f"HTML minification failed: {ex}")


def register():
    """
    Once all HTML files have been generated by pelican, minify each files
    contents using the 'htmlmin' package.

    https://htmlmin.readthedocs.io/en/latest/
    """
    signals.finalized.connect(minify_html)
